### ISSUE TITLE
Keep getting this index out of range error. Any ideas? 

### ISSUE THREAD

**Issue by hyndraslic** [monuyadav016/Saavn-Downloader#27] opened 2020-06-19 04:23 UTC
[
![Error](https://user-images.githubusercontent.com/34486426/85096691-12c71f00-b1c3-11ea-9c12-39f359486eb9.PNG)
](url)

**Comment by vaishakhgarg** [comment] 2020-06-19 08:24
I get the same message. It was working last week!

**Comment by monuyadav016** [comment] 2020-06-19 08:28
It seems the UI was updated. I'll fix it soon.

**Comment by vaishakhgarg** [comment] 2020-06-19 08:45
Actually, you don’t need to. I found a workaround. If you use python3 download_reloaded.py -user -p, it still downloads all the songs from your playlist without any error message. So I have created a dummy account for this purpose. Btw, I love this script, thanks for it. And keep it alive for as long as possible!

On 19Jun, 2020, at 12:28 PM, Monu <notifications@github.com> wrote:


It seems the UI was updated. I'll fix it soon.

**Comment by monuyadav016** [comment] 2020-06-19 08:49
@vaishakhgarg Actually it does. Since many have reported it. Also the functionality for users with accounts is different and does not rely on web scraping the ID for playlist and albums. So changes in UI can break functionality for those using it without having a jiosaavn account.

**Comment by monuyadav016** [comment] 2020-06-19 08:55
Duplicate of #26

**Comment by amail101** [comment] 2020-06-19 11:16
Please fix this error soon.

**Comment by monuyadav016** [comment] 2020-06-19 15:41
@hyndraslic @vaishakhgarg @amail101 A small fix for downloading albums and playlist has been done. I'll have to figure out a fix for artist and individual songs. Download and update the scripts.

**Comment by hyndraslic** [comment] 2020-06-19 15:47
Thank you! It's working for me.now

**Comment by faheembhati** [comment] 2020-06-19 15:48
@monuyadav016 awesome!! I've been refreshing the tab since morning for update.
Please don't ever discontinue this beautiful script.
Thanks a lot!

**Comment by vaishakhgarg** [comment] 2020-06-19 15:54
@monuyadav016 it is not working!!! the terminal is stuck at enter url:

**Comment by vaishakhgarg** [comment] 2020-06-19 15:54
can anyone help, I have reinstalled the script

**Comment by faheembhati** [comment] 2020-06-19 16:10
It got stuck for a minute or two. Then it produced following output:
```
Unable to get albumID:
DONE
```

**Comment by vaishakhgarg** [comment] 2020-06-19 16:14
@faheembhati I don't even get that output

**Comment by monuyadav016** [comment] 2020-06-19 16:19
@faheembhati @vaishakhgarg I know this fix is not perfect because the updated UI is making it slow to obtain the ID. The json embedded in their web pages is broken. Fixing that is slow and the script would feel stuck and at times may not work. I'll have to look more into it. For now I recommend creating a temporary account and using it to download the playlist.

**Comment by vaishakhgarg** [comment] 2020-06-19 16:21
> @faheembhati @vaishakhgarg I know this fix is not perfect because the updated UI is making it slow to obtain the ID. The json embedded in their web pages is broken. Fixing that is slow and the script would feel stuck and at times may not work. I'll have to look more into it. For now I recommend creating a temporary account and using it to download the playlist.

no problem man! the user playlist command is still working, you're awesome!

**Comment by monuyadav016** [comment] 2020-06-20 13:39
@faheembhati @hyndraslic @vaishakhgarg @amail101 I have fixed it properly now. You can update the scripts and test it. Now the downloads should be as fast as it was before.

**Comment by faheembhati** [comment] 2020-06-20 14:00
@monuyadav016 Thanks for the quick update. Let me download and test it.

**Comment by faheembhati** [comment] 2020-06-20 15:03
@monuyadav016 If a directory contains ":" it throws following error:
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\xxxxxx\\Non-Artist\\xxxx: xxxxxx'

**Closed** 2020-06-24 04:04 UTC
Labels: bug
